name: Heroku deploy application

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: GitHub Action for Heroku
        uses: actions/heroku@master

      - name: Login on Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku login

      - name: Add remote from heroku git
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku git:remote -a motorman-staging

      - name: Push and release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: git push heroku-production master:master
